import type { INodeProperties } from 'n8n-workflow';

const countryOptions = [
    { name: 'Germany', value: 'DE' },
    { name: 'Austria', value: 'AT' },
    { name: 'Switzerland', value: 'CH' },
    { name: 'United Kingdom', value: 'GB' },
    { name: 'Italy', value: 'IT' },
    { name: 'Afghanistan', value: 'AF' },
    { name: 'Aland Islands', value: 'AX' },
    { name: 'Albania', value: 'AL' },
    { name: 'Algeria', value: 'DZ' },
    { name: 'American Samoa', value: 'AS' },
    { name: 'Andorra', value: 'AD' },
    { name: 'Angola', value: 'AO' },
    { name: 'Anguilla', value: 'AI' },
    { name: 'Antarctica', value: 'AQ' },
    { name: 'Antigua And Barbuda', value: 'AG' },
    { name: 'Argentina', value: 'AR' },
    { name: 'Armenia', value: 'AM' },
    { name: 'Aruba', value: 'AW' },
    { name: 'Australia', value: 'AU' },
    { name: 'Azerbaijan', value: 'AZ' },
    { name: 'Bahamas', value: 'BS' },
    { name: 'Bahrain', value: 'BH' },
    { name: 'Bangladesh', value: 'BD' },
    { name: 'Barbados', value: 'BB' },
    { name: 'Belarus', value: 'BY' },
    { name: 'Belgium', value: 'BE' },
    { name: 'Belize', value: 'BZ' },
    { name: 'Benin', value: 'BJ' },
    { name: 'Bermuda', value: 'BM' },
    { name: 'Bhutan', value: 'BT' },
    { name: 'Bolivia', value: 'BO' },
    { name: 'Bosnia And Herzegovina', value: 'BA' },
    { name: 'Botswana', value: 'BW' },
    { name: 'Bouvet Island', value: 'BV' },
    { name: 'Brazil', value: 'BR' },
    { name: 'British Indian Ocean Territory', value: 'IO' },
    { name: 'Brunei Darussalam', value: 'BN' },
    { name: 'Bulgaria', value: 'BG' },
    { name: 'Burkina Faso', value: 'BF' },
    { name: 'Burundi', value: 'BI' },
    { name: 'Cambodia', value: 'KH' },
    { name: 'Cameroon', value: 'CM' },
    { name: 'Canada', value: 'CA' },
    { name: 'Cape Verde', value: 'CV' },
    { name: 'Cayman Islands', value: 'KY' },
    { name: 'Central African Republic', value: 'CF' },
    { name: 'Chad', value: 'TD' },
    { name: 'Chile', value: 'CL' },
    { name: 'China', value: 'CN' },
    { name: 'Christmas Island', value: 'CX' },
    { name: 'Cocos (Keeling) Islands', value: 'CC' },
    { name: 'Colombia', value: 'CO' },
    { name: 'Comoros', value: 'KM' },
    { name: 'Congo', value: 'CG' },
    { name: 'Congo, Democratic Republic', value: 'CD' },
    { name: 'Cook Islands', value: 'CK' },
    { name: 'Costa Rica', value: 'CR' },
    { name: 'Cote D\'Ivoire', value: 'CI' },
    { name: 'Croatia', value: 'HR' },
    { name: 'Cuba', value: 'CU' },
    { name: 'Cyprus', value: 'CY' },
    { name: 'Czech Republic', value: 'CZ' },
    { name: 'Denmark', value: 'DK' },
    { name: 'Djibouti', value: 'DJ' },
    { name: 'Dominica', value: 'DM' },
    { name: 'Dominican Republic', value: 'DO' },
    { name: 'Ecuador', value: 'EC' },
    { name: 'Egypt', value: 'EG' },
    { name: 'El Salvador', value: 'SV' },
    { name: 'Equatorial Guinea', value: 'GQ' },
    { name: 'Eritrea', value: 'ER' },
    { name: 'Estonia', value: 'EE' },
    { name: 'Ethiopia', value: 'ET' },
    { name: 'Falkland Islands', value: 'FK' },
    { name: 'Faroe Islands', value: 'FO' },
    { name: 'Fiji', value: 'FJ' },
    { name: 'Finland', value: 'FI' },
    { name: 'France', value: 'FR' },
    { name: 'French Guiana', value: 'GF' },
    { name: 'French Polynesia', value: 'PF' },
    { name: 'French Southern Territories', value: 'TF' },
    { name: 'Gabon', value: 'GA' },
    { name: 'Gambia', value: 'GM' },
    { name: 'Georgia', value: 'GE' },
    { name: 'Ghana', value: 'GH' },
    { name: 'Gibraltar', value: 'GI' },
    { name: 'Greece', value: 'GR' },
    { name: 'Greenland', value: 'GL' },
    { name: 'Grenada', value: 'GD' },
    { name: 'Guadeloupe', value: 'GP' },
    { name: 'Guam', value: 'GU' },
    { name: 'Guatemala', value: 'GT' },
    { name: 'Guernsey', value: 'GG' },
    { name: 'Guinea', value: 'GN' },
    { name: 'Guinea-Bissau', value: 'GW' },
    { name: 'Guyana', value: 'GY' },
    { name: 'Haiti', value: 'HT' },
    { name: 'Heard Island & Mcdonald Islands', value: 'HM' },
    { name: 'Holy See (Vatican City State)', value: 'VA' },
    { name: 'Honduras', value: 'HN' },
    { name: 'Hong Kong', value: 'HK' },
    { name: 'Hungary', value: 'HU' },
    { name: 'Iceland', value: 'IS' },
    { name: 'India', value: 'IN' },
    { name: 'Indonesia', value: 'ID' },
    { name: 'Iran', value: 'IR' },
    { name: 'Iraq', value: 'IQ' },
    { name: 'Ireland', value: 'IE' },
    { name: 'Isle Of Man', value: 'IM' },
    { name: 'Israel', value: 'IL' },
    { name: 'Jamaica', value: 'JM' },
    { name: 'Japan', value: 'JP' },
    { name: 'Jersey', value: 'JE' },
    { name: 'Jordan', value: 'JO' },
    { name: 'Kazakhstan', value: 'KZ' },
    { name: 'Kenya', value: 'KE' },
    { name: 'Kiribati', value: 'KI' },
    { name: 'Korea', value: 'KR' },
    { name: 'Kuwait', value: 'KW' },
    { name: 'Kyrgyzstan', value: 'KG' },
    { name: 'Lao People\'s Democratic Republic', value: 'LA' },
    { name: 'Latvia', value: 'LV' },
    { name: 'Lebanon', value: 'LB' },
    { name: 'Lesotho', value: 'LS' },
    { name: 'Liberia', value: 'LR' },
    { name: 'Libya', value: 'LY' },
    { name: 'Liechtenstein', value: 'LI' },
    { name: 'Lithuania', value: 'LT' },
    { name: 'Luxembourg', value: 'LU' },
    { name: 'Macao', value: 'MO' },
    { name: 'Madagascar', value: 'MG' },
    { name: 'Malawi', value: 'MW' },
    { name: 'Malaysia', value: 'MY' },
    { name: 'Maldives', value: 'MV' },
    { name: 'Mali', value: 'ML' },
    { name: 'Malta', value: 'MT' },
    { name: 'Marshall Islands', value: 'MH' },
    { name: 'Martinique', value: 'MQ' },
    { name: 'Mauritania', value: 'MR' },
    { name: 'Mauritius', value: 'MU' },
    { name: 'Mayotte', value: 'YT' },
    { name: 'Mexico', value: 'MX' },
    { name: 'Micronesia', value: 'FM' },
    { name: 'Moldova', value: 'MD' },
    { name: 'Monaco', value: 'MC' },
    { name: 'Mongolia', value: 'MN' },
    { name: 'Montenegro', value: 'ME' },
    { name: 'Montserrat', value: 'MS' },
    { name: 'Morocco', value: 'MA' },
    { name: 'Mozambique', value: 'MZ' },
    { name: 'Myanmar', value: 'MM' },
    { name: 'Namibia', value: 'NA' },
    { name: 'Nauru', value: 'NR' },
    { name: 'Nepal', value: 'NP' },
    { name: 'Netherlands', value: 'NL' },
    { name: 'New Caledonia', value: 'NC' },
    { name: 'New Zealand', value: 'NZ' },
    { name: 'Nicaragua', value: 'NI' },
    { name: 'Niger', value: 'NE' },
    { name: 'Nigeria', value: 'NG' },
    { name: 'Niue', value: 'NU' },
    { name: 'Norfolk Island', value: 'NF' },
    { name: 'Northern Mariana Islands', value: 'MP' },
    { name: 'Norway', value: 'NO' },
    { name: 'Oman', value: 'OM' },
    { name: 'Pakistan', value: 'PK' },
    { name: 'Palau', value: 'PW' },
    { name: 'Panama', value: 'PA' },
    { name: 'Papua New Guinea', value: 'PG' },
    { name: 'Paraguay', value: 'PY' },
    { name: 'Peru', value: 'PE' },
    { name: 'Philippines', value: 'PH' },
    { name: 'Pitcairn', value: 'PN' },
    { name: 'Poland', value: 'PL' },
    { name: 'Portugal', value: 'PT' },
    { name: 'Puerto Rico', value: 'PR' },
    { name: 'Qatar', value: 'QA' },
    { name: 'Romania', value: 'RO' },
    { name: 'Russian Federation', value: 'RU' },
    { name: 'Rwanda', value: 'RW' },
    { name: 'Reunion', value: 'RE' },
    { name: 'Saint Barthelemy', value: 'BL' },
    { name: 'Saint Helena', value: 'SH' },
    { name: 'Saint Kitts And Nevis', value: 'KN' },
    { name: 'Saint Lucia', value: 'LC' },
    { name: 'Saint Martin', value: 'MF' },
    { name: 'Saint Pierre And Miquelon', value: 'PM' },
    { name: 'Saint Vincent And The Grenadines', value: 'VC' },
    { name: 'Samoa', value: 'WS' },
    { name: 'San Marino', value: 'SM' },
    { name: 'Sao Tome And Principe', value: 'ST' },
    { name: 'Saudi Arabia', value: 'SA' },
    { name: 'Senegal', value: 'SN' },
    { name: 'Serbia', value: 'RS' },
    { name: 'Seychelles', value: 'SC' },
    { name: 'Sierra Leone', value: 'SL' },
    { name: 'Singapore', value: 'SG' },
    { name: 'Sint Maarten', value: 'SX' },
    { name: 'Slovakia', value: 'SK' },
    { name: 'Slovenia', value: 'SI' },
    { name: 'Solomon Islands', value: 'SB' },
    { name: 'Somalia', value: 'SO' },
    { name: 'South Africa', value: 'ZA' },
    { name: 'South Georgia And The South Sandwich Islands', value: 'GS' },
    { name: 'South Sudan', value: 'SS' },
    { name: 'Spain', value: 'ES' },
    { name: 'Sri Lanka', value: 'LK' },
    { name: 'Sudan', value: 'SD' },
    { name: 'Suriname', value: 'SR' },
    { name: 'Svalbard And Jan Mayen', value: 'SJ' },
    { name: 'Sweden', value: 'SE' },
    { name: 'Switzerland', value: 'CH' },
    { name: 'Syrian Arab Republic', value: 'SY' },
    { name: 'Taiwan', value: 'TW' },
    { name: 'Tajikistan', value: 'TJ' },
    { name: 'Tanzania', value: 'TZ' },
    { name: 'Thailand', value: 'TH' },
    { name: 'Timor-Leste', value: 'TL' },
    { name: 'Togo', value: 'TG' },
    { name: 'Tokelau', value: 'TK' },
    { name: 'Tonga', value: 'TO' },
    { name: 'Trinidad And Tobago', value: 'TT' },
    { name: 'Tunisia', value: 'TN' },
    { name: 'Turkey', value: 'TR' },
    { name: 'Turkmenistan', value: 'TM' },
    { name: 'Tuvalu', value: 'TV' },
    { name: 'Uganda', value: 'UG' },
    { name: 'Ukraine', value: 'UA' },
    { name: 'United Arab Emirates', value: 'AE' },
    { name: 'United Kingdom', value: 'GB' },
    { name: 'United States', value: 'US' },
    { name: 'Uruguay', value: 'UY' },
    { name: 'Uzbekistan', value: 'UZ' },
    { name: 'Vanuatu', value: 'VU' },
    { name: 'Venezuela', value: 'VE' },
    { name: 'Viet Nam', value: 'VN' },
    { name: 'Western Sahara', value: 'EH' },
    { name: 'Yemen', value: 'YE' },
    { name: 'Zambia', value: 'ZM' },
    { name: 'Zimbabwe', value: 'ZW' }
]

export const contactOperations: INodeProperties[] = [
    {
        displayName: 'Operation',
        name: 'operation',
        type: 'options',
        noDataExpression: true,
        displayOptions: {
            show: {
                resource: ['contact'],
            },
        },
        options: [
            {
                name: 'Create',
                value: 'create',
                action: 'Create Contact',
            },
            {
                name: 'Update',
                value: 'update',
                action: 'Update Contact',
            },
            {
                name: 'Get',
                value: 'get',
                action: 'List Contacts',
            },
            {
                name: 'Delete',
                value: 'delete',
                action: 'Delete Contact',
            },
            {
                name: 'Set Value',
                value: 'setValue',
                action: 'Set Field-Value',
            },
            {
                name: 'Get Value',
                value: 'getValue',
                action: 'Get Field-Value',
            },
            {
                name: 'Add a Tag',
                value: 'addATag',
                action: 'Add Tags',
            },
            {
                name: 'Remove a Tag',
                value: 'removeATag',
                action: 'Remove Tags',
            },
            {
                name: 'Get Field List',
                value: 'getContactFieldList',
                action: 'List Field-Values',
            },
            {
                name: 'Get Tag List',
                value: 'getContactTagList',
                action: 'List Tags',
            },
        ],

        default: 'create',
    },
];

export const contactFields: INodeProperties[] = [
    // ----------------------------------------
    //             contact: create
    //             basis fields
    // ----------------------------------------
    {
        displayName: 'Firstname',
        name: 'contactFirstname',
        type: 'string',
        default: '',

        displayOptions: {
            show: {
                resource: ['contact'],
                operation: ['create'],
            },
        },
        placeholder: 'Contact firstname',
        description: 'The firstname of the contact',
    },
    {
        displayName: 'Lastname',
        name: 'contactLastname',
        type: 'string',
        default: '',

        displayOptions: {
            show: {
                resource: ['contact'],
                operation: ['create'],
            },
        },
        placeholder: 'Contact lastname',
        description: 'The lastname of the contact',
    },
    {
        displayName: 'E-Mail',
        name: 'contactEmail',
        type: 'string',
        default: '',
        required: true,
        displayOptions: {
            show: {
                resource: ['contact'],
                operation: ['create'],
            },
        },
        placeholder: 'Contact E-Mail',
        description: 'The E-Mail of the contact',
    },
    {
        displayName: 'Mobile',
        name: 'contactMobile',
        type: 'string',
        default: '',

        displayOptions: {
            show: {
                resource: ['contact'],
                operation: ['create'],
            },
        },
        placeholder: 'Contact mobile number',
        description: 'The mobile number of the contact',
    },
    // ----------------------------------------
    //        contact: update, get, delete, 
    //        getContactTagList, getContactFieldList,
    //        addATag, removeATag
    // ----------------------------------------
    {
        displayName: 'The email of a contact can be used as an alternative ID.',
        name: 'notice',
        type: 'notice',
        default: '',
        displayOptions: {
            show: {
                resource: ['contact'],
                operation: ['update', 'delete',
                    'addATag', 'removeATag',
                    'getContactTagList', 'getContactFieldList'],
            },
        },
    },
    {
        displayName: 'Contact',
        name: 'contactId',
        type: 'resourceLocator',
        required: true,
        default: { mode: 'id', value: '' },
        placeholder: 'Select a contact...',
        description: 'Select a contact',
        displayOptions: {
            show: {
                resource: ['contact'],
                operation: ['update', 'delete',
                    'addATag', 'removeATag',
                    'getContactTagList', 'getContactFieldList'],
            },
        },
        modes: [
            {
                displayName: 'From List',
                name: 'list',
                type: 'list',
                placeholder: 'Select a contact...',
                typeOptions: {
                    searchListMethod: 'getContacts',
                    searchable: true,
                },
            },
            {
                displayName: 'By ID',
                name: 'id',
                type: 'string',
            },
        ],
    },
    // ----------------------------------------
    //             contact: create
    //             all other fields
    // ----------------------------------------
    {
        displayName: 'Additional Fields',
        name: 'contactCreateFields',
        type: 'collection',
        placeholder: 'Add Field',
        default: {},
        displayOptions: {
            show: {
                resource: [
                    'contact',
                ],
                operation: [
                    'create',
                ],
            },
        },
        options: [
            {
                displayName: 'Salutation',
                name: 'contactSalutation',
                type: 'options',
                default: 'm',
                description: 'Select the salutation for the contact',
                options: [
                    {
                        name: 'Herr',
                        value: 'm',
                    },
                    {
                        name: 'Frau',
                        value: 'f',
                    },
                    {
                        name: 'Divers',
                        value: 'd',
                    },
                ],
            },
            {
                displayName: 'Company',
                name: 'contactCompany',
                type: 'string',
                default: '',
                description: 'Select the company for the contact',
            },
            {
                displayName: 'Phone Number',
                name: 'contactPhoneNumber',
                type: 'string',
                default: '',
                description: 'Select the phone number for the contact',
            },
            {
                displayName: 'Birthday',
                name: 'contactBirthday',
                type: 'dateTime',
                default: '',
                description: 'Select the birthday for the contact',
            },
            {
                displayName: 'Position (Company)',
                name: 'contactPosition',
                type: 'string',
                default: '',
                description: 'Select the position for the contact',
            },
            {
                displayName: 'Country',
                name: 'contactCountry',
                type: 'options',
                default: '',
                description: 'Select the country for the contact',
                options: countryOptions,
            },
            {
                displayName: 'Street',
                name: 'contactStreet',
                type: 'string',
                default: '',
                description: 'Select the street for the contact',
            },
            {
                displayName: 'Street Number',
                name: 'contactHouseNumber',
                type: 'string',
                default: '',
                description: 'Select the street number for the contact',
            },
            {
                displayName: 'ZIP Code',
                name: 'contactZip',
                type: 'string',
                default: '',
                description: 'Select the zip code for the contact',
            },
            {
                displayName: 'City',
                name: 'contactCity',
                type: 'string',
                default: '',
                description: 'Select the city for the contact',
            },
            {
                displayName: 'Fax',
                name: 'contactFax',
                type: 'string',
                default: '',
                description: 'Select the fax for the contact',
            },
            {
                displayName: 'Website',
                name: 'contactWebsite',
                type: 'string',
                default: '',
                description: 'Select the website for the contact',
            },
            {
                displayName: 'Skype',
                name: 'contactSkype',
                type: 'string',
                default: '',
                description: 'Select the skype for the contact',
            },
        ],
    },
    // ----------------------------------------
    //             contact: update
    //             all fields
    // ----------------------------------------
    {
        displayName: 'Additional Fields',
        name: 'contactUpdateFields',
        type: 'collection',
        placeholder: 'Add Field',
        default: {},
        displayOptions: {
            show: {
                resource: [
                    'contact',
                ],
                operation: [
                    'update',
                ],
            },
        },
        options: [
            {
                displayName: 'Firstname',
                name: 'contactFirstname',
                type: 'string',
                default: '',
                placeholder: 'Contact firstname',
                description: 'The firstname of the contact',
            },
            {
                displayName: 'Lastname',
                name: 'contactLastname',
                type: 'string',
                default: '',
                placeholder: 'Contact lastname',
                description: 'The lastname of the contact',
            },
            {
                displayName: 'E-Mail',
                name: 'contactEmail',
                type: 'string',
                default: '',
                placeholder: 'Contact E-Mail',
                description: 'The E-Mail of the contact',
            },
            {
                displayName: 'Mobile',
                name: 'contactMobile',
                type: 'string',
                default: '',
                description: 'The mobile number of the contact',
            },
            {
                displayName: 'Salutation',
                name: 'contactSalutation',
                type: 'options',
                default: 'm',
                description: 'Select the salutation for the contact',
                options: [
                    {
                        name: 'Herr',
                        value: 'm',
                    },
                    {
                        name: 'Frau',
                        value: 'f',
                    },
                    {
                        name: 'Divers',
                        value: 'd',
                    },
                ],
            },
            {
                displayName: 'Company',
                name: 'contactCompany',
                type: 'string',
                default: '',
                description: 'Select the company for the contact',
            },
            {
                displayName: 'Phone Number',
                name: 'contactPhoneNumber',
                type: 'string',
                default: '',
                description: 'Select the phone number for the contact',
            },
            {
                displayName: 'Birthday',
                name: 'contactBirthday',
                type: 'dateTime',
                default: '',
                description: 'Select the birthday for the contact',
            },
            {
                displayName: 'Position (Company)',
                name: 'contactPosition',
                type: 'string',
                default: '',
                description: 'Select the position for the contact',
            },
            {
                displayName: 'Country',
                name: 'contactCountry',
                type: 'options',
                default: '',
                description: 'Select the country for the contact',
                options: countryOptions,
            },
            {
                displayName: 'Street',
                name: 'contactStreet',
                type: 'string',
                default: '',
                description: 'Select the street for the contact',
            },
            {
                displayName: 'Street Number',
                name: 'contactHouseNumber',
                type: 'string',
                default: '',
                description: 'Select the street number for the contact',
            },
            {
                displayName: 'ZIP Code',
                name: 'contactZip',
                type: 'string',
                default: '',
                description: 'Select the zip code for the contact',
            },
            {
                displayName: 'City',
                name: 'contactCity',
                type: 'string',
                default: '',
                description: 'Select the city for the contact',
            },
            {
                displayName: 'Fax',
                name: 'contactFax',
                type: 'string',
                default: '',
                description: 'Select the fax for the contact',
            },
            {
                displayName: 'Website',
                name: 'contactWebsite',
                type: 'string',
                default: '',
                description: 'Select the website for the contact',
            },
            {
                displayName: 'Skype',
                name: 'contactSkype',
                type: 'string',
                default: '',
                description: 'Select the skype for the contact',
            },
        ],
    },
    // ----------------------------------------
    //             contact: get
    // ----------------------------------------
    {
        displayName: 'The email of a contact can be used as an alternative ID.',
        name: 'notice',
        type: 'notice',
        default: '',
        displayOptions: {
            show: {
                resource: ['contact'],
                operation: ['get'],
                bReturnAll: [false]
            },
        },
    },
    {
        displayName: 'Contact',
        name: 'contactId',
        type: 'resourceLocator',
        required: true,
        default: { mode: 'id', value: '' },
        placeholder: 'Select a contact...',
        description: 'Select a contact',
        displayOptions: {
            show: {
                resource: ['contact'],
                operation: ['get'],
                bReturnAll: [false]
            },
        },
        modes: [
            {
                displayName: 'From List',
                name: 'list',
                type: 'list',
                placeholder: 'Select a contact...',
                typeOptions: {
                    searchListMethod: 'getContacts',
                    searchable: true,
                },
            },
            {
                displayName: 'By ID',
                name: 'id',
                type: 'string',
            },
        ],
    },
    {
        displayName: 'Search for multiple results',
        name: 'bReturnAll',
        type: 'boolean',
        displayOptions: {
            show: {
                operation: ['get'],
                resource: ['contact'],
            },
        },
        default: false,
        description: 'Whether to return a single object or a list of objects',
    },
    {
        displayName: 'Additional Fields',
        name: 'contactQs',
        type: 'collection',
        placeholder: 'Add Field',
        default: {},
        displayOptions: {
            show: {
                resource: [
                    'contact',
                ],
                operation: [
                    'get',
                ],
                bReturnAll: [true],
            },
        },
        options: [
            {
                displayName: 'Search String',
                name: 'contactSearchString',
                type: 'string',
                default: '',
                description: 'This parameter is used to specify the text you want to search for within the name fields. For example, if you\'re looking for names containing "@muster.de", you would enter this value in the searchString parameter.',
            },
            {
                displayName: 'Page Size',
                name: 'contactPageSize',
                type: 'number',
                default: '',
                description: 'This parameter defines the number of results to display per page. You can specify values like 5, 10, 20, 50, or 200, depending on how many results you want to be shown per page in the response.',
            },
            {
                displayName: 'Page Number',
                name: 'contactPageNum',
                type: 'number',
                default: '',
                description: 'This parameter is used to indicate the page number you want to retrieve in the result set. For example, if you want the first set of results, you would set this value to 1. If you want the second set, set it to 2, and so on.',
            },
        ],
    },
    // ----------------------------------------
    //       contact: addATag, removeATag
    // ----------------------------------------
    {
        displayName: 'Edit a List of Tags',
        name: 'bListOfTags',
        type: 'boolean',
        displayOptions: {
            show: {
                operation: ['addATag', 'removeATag'],
                resource: ['contact'],
            },
        },
        default: false,
        description: 'Whether to provide a list of tags to add or remove from a contact when enabled',
    },
    {
        displayName: 'Tag Names or IDs',
        name: 'contactTagIdList',
        type: 'multiOptions',
        default: [],
        placeholder: 'Select one or more tags...',
        description: 'Select one or more tags from the list. Choose from the list, or specify IDs using an <a href="https://docs.n8n.io/code-examples/expressions/">expression</a>.',
        displayOptions: {
            show: {
                resource: ['contact'],
                operation: ['addATag', 'removeATag'],
                bListOfTags: [true],
            },
        },
        typeOptions: {
            loadOptionsMethod: 'getTags',
        },
    },
    {
        displayName: 'Tag',
        name: 'contactTagId',
        type: 'resourceLocator',
        default: { mode: 'list', value: '' },
        placeholder: 'Select a tag...',
        description: 'Select a tag',
        displayOptions: {
            show: {
                resource: ['contact'],
                operation: ['addATag', 'removeATag'],
                bListOfTags: [false]
            },
        },
        modes: [
            {
                displayName: 'From List',
                name: 'list',
                type: 'list',
                placeholder: 'Select a tag...',
                typeOptions: {
                    searchListMethod: 'getTags',
                    searchable: true,
                },
            },
            {
                displayName: 'By ID',
                name: 'id',
                type: 'string',
                validation: [
                    {
                        type: 'regex',
                        properties: {
                            regex: '^[0-9]*$',
                            errorMessage: 'Not a valid tag ID',
                        },
                    },
                ],
            },
        ],
    },




    {
        displayName: 'Set Multiple Fields',
        name: 'bSetMultiFields',
        type: 'boolean',
        default: false,
        displayOptions: {
            show: {
                resource: ['contact'],
                operation: ['setValue'],
            },
        },
        description: 'Whether to enable this option to set multiple fields at once',
    },
    {
        displayName: 'Global Field',
        name: 'globalFieldId',
        type: 'resourceLocator',
        required: true,
        default: { mode: 'list', value: '' },
        placeholder: 'Select a global field...',
        description: 'Select a global field',
        displayOptions: {
            show: {
                resource: ['contact'],
                operation: ['getValue'],
            },
        },
        modes: [
            {
                displayName: 'From List',
                name: 'list',
                type: 'list',
                placeholder: 'Select a global field...',
                typeOptions: {
                    searchListMethod: 'getGlobalFields',
                    searchable: true,
                },
            },
            {
                displayName: 'By ID',
                name: 'id',
                type: 'string',
                validation: [
                    {
                        type: 'regex',
                        properties: {
                            regex: '^[0-9]*$',
                            errorMessage: 'Not a valid global field ID',
                        },
                    },
                ],
            },
        ],
    },
    {
        displayName: 'Global Field',
        name: 'globalFieldId',
        type: 'resourceLocator',
        required: true,
        default: { mode: 'list', value: '' },
        placeholder: 'Select a global field...',
        description: 'Select a global field',
        displayOptions: {
            show: {
                resource: ['contact'],
                operation: ['setValue'],
                bSetMultiFields: [false],
            },
        },
        modes: [
            {
                displayName: 'From List',
                name: 'list',
                type: 'list',
                placeholder: 'Select a global field...',
                typeOptions: {
                    searchListMethod: 'getGlobalFields',
                    searchable: true,
                },
            },
            {
                displayName: 'By ID',
                name: 'id',
                type: 'string',
                validation: [
                    {
                        type: 'regex',
                        properties: {
                            regex: '^[0-9]*$',
                            errorMessage: 'Not a valid global field ID',
                        },
                    },
                ],
            },
        ],
    },
    {
        displayName: 'The email of a contact can be used as an alternative ID.',
        name: 'notice',
        type: 'notice',
        default: '',
        displayOptions: {
            show: {
                resource: ['contact'],
                operation: ['getValue', 'setValue'],
            },
        },
    },
    {
        displayName: 'Contact',
        name: 'globalFieldContactId',
        type: 'resourceLocator',
        required: true,
        default: { mode: 'id', value: '' },
        placeholder: 'Select a contact...',
        description: 'Select a contact',
        displayOptions: {
            show: {
                resource: ['contact'],
                operation: ['getValue', 'setValue'],
            },
        },
        modes: [
            {
                displayName: 'From List',
                name: 'list',
                type: 'list',
                placeholder: 'Select a contact...',
                typeOptions: {
                    searchListMethod: 'getContacts',
                    searchable: true,
                },
            },
            {
                displayName: 'By ID',
                name: 'id',
                type: 'string',
            },
        ],
    },
    {
        displayName: 'Fields to Set (Max. 20)',
        name: 'fieldsToSet',
        type: 'fixedCollection',
        placeholder: 'Add Field',
        default: {},
        typeOptions: {
            multipleValues: true,
        },
        displayOptions: {
            show: {
                resource: ['contact'],
                operation: ['setValue'],
                bSetMultiFields: [true],
            },
        },
        options: [
            {
                name: 'field',
                displayName: 'Field',
                values: [
                    {
                        displayName: 'Global Field',
                        name: 'globalFieldId',
                        type: 'resourceLocator',
                        required: true,
                        default: { mode: 'list', value: '' },
                        placeholder: 'Select a global field...',
                        description: 'Select a global field',
                        modes: [
                            {
                                displayName: 'From List',
                                name: 'list',
                                type: 'list',
                                placeholder: 'Select a global field...',
                                typeOptions: {
                                    searchListMethod: 'getGlobalFields',
                                    searchable: true,
                                },
                            },
                            {
                                displayName: 'By ID',
                                name: 'id',
                                type: 'string',
                                validation: [
                                    {
                                        type: 'regex',
                                        properties: {
                                            regex: '^[0-9]*$',
                                            errorMessage: 'Not a valid global field ID',
                                        },
                                    },
                                ],
                            },
                        ],
                    },
                    {
                        displayName: 'Value',
                        name: 'value',
                        type: 'string',
                        required: true,
                        default: '',
                        description: 'Whether to set this value for the field',
                    },
                    {
                        displayName: 'Do Triggers',
                        name: 'doTriggers',
                        type: 'boolean',
                        default: false,
                        description: 'Whether to enable or disable triggers for this field',
                    },
                    {
                        displayName: 'Overwrite',
                        name: 'overwrite',
                        type: 'boolean',
                        default: false,
                        description: 'Whether to enable or disable overwriting existing values',
                    },
                ],
            },
        ],
    },
    {
        displayName: 'Value',
        name: 'globalFieldValue',
        type: 'string',
        default: '',
        required: true,
        displayOptions: {
            show: {
                resource: ['contact'],
                operation: ['setValue'],
                bSetMultiFields: [false],
            },
        },
        description: 'The value to set for this field',
    },
    {
        displayName: 'Do Triggers',
        name: 'bDoTriggers',
        type: 'boolean',
        default: false,

        displayOptions: {
            show: {
                operation: ['setValue'],
                resource: ['contact'],
                bSetMultiFields: [false],
            },
        },
        description: 'Whether an automatic process, which normally listens to a value change, should be triggered',
    },
    {
        displayName: 'Overwrite',
        name: 'bOverwrite',
        type: 'boolean',
        default: false,

        displayOptions: {
            show: {
                operation: ['setValue'],
                resource: ['contact'],
                bSetMultiFields: [false],
            },
        },
        description: 'Whether an already present value should be overwritten',
    },
];